In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [24]:
dataset = pd.read_csv('./property Sales of Melbourne City.csv')
dataset.head()

,Unnamed: 0,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,1,Abbotsford,85 Turner St,2,h,1480000,S,Biggin,3/12/2016,2.5,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,2,Abbotsford,25 Bloomburg St,2,h,1035000,S,Biggin,4/02/2016,2.5,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,4,Abbotsford,5 Charles St,3,h,1465000,SP,Biggin,4/03/2017,2.5,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0
3,5,Abbotsford,40 Federation La,3,h,850000,PI,Biggin,4/03/2017,2.5,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0
4,6,Abbotsford,55a Park St,4,h,1600000,VB,Nelson,4/06/2016,2.5,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0

In [25]:
dataset.nunique()

Unnamed: 0       18396
Suburb             330
Address          18134
Rooms               11
Type                 3
Price             2470
Method               5
SellerG            305
Date                58
Distance           210
Postcode           205
Bedroom2            12
Bathroom             9
Car                 11
Landsize          1449
BuildingArea       613
YearBuilt          144
CouncilArea         33
Lattitude         7518
Longtitude        8168
Regionname           8
Propertycount      324
dtype: int64

In [26]:
dataset.shape

(18396, 22)

In [27]:
cols_to_use = ['Suburb','Rooms','Price','Type','Method','SellerG','Regionname','Propertycount','Distance','Bedroom2','Bathroom','Car','Landsize','BuildingArea','CouncilArea']
dataset = dataset[cols_to_use]
dataset.head()

,Suburb,Rooms,Price,Type,Method,SellerG,Regionname,Propertycount,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,CouncilArea
0,Abbotsford,2,1480000,h,S,Biggin,Northern Metropolitan,4019.0,2.5,2.0,1.0,1.0,202.0,NaN,Yarra
1,Abbotsford,2,1035000,h,S,Biggin,Northern Metropolitan,4019.0,2.5,2.0,1.0,0.0,156.0,79.0,Yarra
2,Abbotsford,3,1465000,h,SP,Biggin,Northern Metropolitan,4019.0,2.5,3.0,2.0,0.0,134.0,150.0,Yarra
3,Abbotsford,3,850000,h,PI,Biggin,Northern Metropolitan,4019.0,2.5,3.0,2.0,1.0,94.0,NaN,Yarra
4,Abbotsford,4,1600000,h,VB,Nelson,Northern Metropolitan,4019.0,2.5,3.0,1.0,2.0,120.0,142.0,Yarra

In [28]:
dataset.shape

(18396, 15)

In [29]:
dataset.isna().sum()

Suburb               0
Rooms                0
Price                0
Type                 0
Method               0
SellerG              0
Regionname           1
Propertycount        1
Distance             1
Bedroom2          3469
Bathroom          3471
Car               3576
Landsize          4793
BuildingArea     10634
CouncilArea       6163
dtype: int64

In [30]:
cols_to_fill_zero = ['Propertycount', 'Distance', 'Bedroom2', 'Bathroom', 'Car']
dataset[cols_to_fill_zero] = dataset[cols_to_fill_zero].fillna(0)
dataset.isna().sum()

Suburb               0
Rooms                0
Price                0
Type                 0
Method               0
SellerG              0
Regionname           1
Propertycount        0
Distance             0
Bedroom2             0
Bathroom             0
Car                  0
Landsize          4793
BuildingArea     10634
CouncilArea       6163
dtype: int64

In [31]:
dataset['Landsize'] = dataset['Landsize'].fillna(dataset.Landsize.mean())
dataset['BuildingArea'] = dataset['BuildingArea'].fillna(dataset.BuildingArea.mean())

In [32]:
dataset.isna().sum()

Suburb              0
Rooms               0
Price               0
Type                0
Method              0
SellerG             0
Regionname          1
Propertycount       0
Distance            0
Bedroom2            0
Bathroom            0
Car                 0
Landsize            0
BuildingArea        0
CouncilArea      6163
dtype: int64

In [34]:
dataset.dropna(inplace=True)
dataset.isna().sum()

Suburb           0
Rooms            0
Price            0
Type             0
Method           0
SellerG          0
Regionname       0
Propertycount    0
Distance         0
Bedroom2         0
Bathroom         0
Car              0
Landsize         0
BuildingArea     0
CouncilArea      0
dtype: int64

In [35]:
dataset = pd.get_dummies(dataset, drop_first=True)
dataset.head()

,Rooms,Price,Propertycount,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Suburb_Aberfeldie,...,CouncilArea_Moreland,CouncilArea_Nillumbik,CouncilArea_Port Phillip,CouncilArea_Stonnington,CouncilArea_Unavailable,CouncilArea_Whitehorse,CouncilArea_Whittlesea,CouncilArea_Wyndham,CouncilArea_Yarra,CouncilArea_Yarra Ranges
0,2,1480000,4019.0,2.5,2.0,1.0,1.0,202.0,151.220219,False,...,False,False,False,False,False,False,False,False,True,False
1,2,1035000,4019.0,2.5,2.0,1.0,0.0,156.0,79.000000,False,...,False,False,False,False,False,False,False,False,True,False
2,3,1465000,4019.0,2.5,3.0,2.0,0.0,134.0,150.000000,False,...,False,False,False,False,False,False,False,False,True,False
3,3,850000,4019.0,2.5,3.0,2.0,1.0,94.0,151.220219,False,...,False,False,False,False,False,False,False,False,True,False
4,4,1600000,4019.0,2.5,3.0,1.0,2.0,120.0,142.000000,False,...,False,False,False,False,False,False,False,False,True,False

In [36]:
X = dataset.drop('Price', axis = 1)
y = dataset['Price']

In [37]:
from sklearn.model_selection import train_test_split
train_X,test_X,train_y,test_y = train_test_split(X,y, test_size =0.3, random_state = 2)

In [39]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression().fit(train_X, train_y)

In [40]:
reg.score(test_X, test_y)

0.6648954535499536

In [41]:
reg.score(train_X, train_y)

0.7100072899187205

In [53]:
from sklearn import linear_model
lasso_reg = linear_model.Lasso(alpha=50, max_iter=100, tol=0.1)
lasso_reg.fit(train_X,train_y)

Lasso(alpha=50, max_iter=100, tol=0.1)

In [54]:
lasso_reg.score(test_X,test_y)

0.6703450094534258

In [56]:
lasso_reg.score(train_X,train_y)

0.7059060292458545

In [57]:
from sklearn.linear_model import Ridge
ridge_reg = Ridge(alpha=50, max_iter=100, tol=0.1)
ridge_reg.fit(train_X,train_y)

Ridge(alpha=50, max_iter=100, tol=0.1)

In [58]:
ridge_reg.score(test_X,test_y)

0.6612473627638111

In [60]:
ridge_reg.score(train_X,train_y)

0.6767852914122192